version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_api
    ports:
      - "8000:8000"
    environment:
      CONFIG_FILE: ".prod.env"
      SQLALCHEMY_WARN_20: 0
    entrypoint: >
      sh -c "
        python3 main.py
      "
    networks:
      - web_main_api
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  cache_data:
    image: redis:latest
    container_name: redis-db
    volumes:
      - redis_data:/var/lib/redis/data/
    expose:
      - 6379
    env_file:
      - ".prod.env"
    networks:
      - web_main_api
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15.1-alpine
    container_name: db-pg
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ".prod.env"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web_main_api


volumes:
  postgres_data:
  redis_data:

networks:
  web_main_api:
    name: web_main_api
