version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_api
    ports:
      - "8000:8000"
    environment:
      CONFIG_FILE: "cfg.ini"
      SQLALCHEMY_WARN_20: 0
    entrypoint: >
      sh -c "
        python3 main.py
      "
    networks:
      - web_main_api
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: db-pg
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=menu_app
    restart: on-failure
    networks:
      - web_main_api


volumes:
  postgres_data:

networks:
  web_main_api:
    name: web_main_api
